SHOW DATABASES;
USE sql_projects;
SHOW TABLES;
SELECT * FROM customer LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(`purchase_amount_(usd)`) AS TOTAL_REVENUE 
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,`purchase_amount_(usd)` FROM CUSTOMER
WHERE `purchase_amount_(usd)`>(SELECT AVG(`purchase_amount_(usd)`) FROM customer) AND discount_applied='Yes'
ORDER BY `purchase_amount_(usd)` DESC;

