SHOW DATABASES;
USE sql_projects;
SHOW TABLES;
SELECT * FROM customer LIMIT 10;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(`purchase_amount_(usd)`) AS TOTAL_REVENUE 
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,`purchase_amount_(usd)` FROM CUSTOMER
WHERE `purchase_amount_(usd)`>(SELECT AVG(`purchase_amount_(usd)`) FROM customer) AND discount_applied='Yes'
ORDER BY `purchase_amount_(usd)` DESC;

-- Q3. Which are the top 5 products with the highest average review rating?  
SELECT DISTINCT item_purchased,ROUND(AVG(review_rating),2) AS AVG_Rating
FROM CUSTOMER
GROUP BY item_purchased
ORDER BY AVG_Rating DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,AVG(`purchase_amount_(usd)`) AS Average_Purchase_Amount
FROM CUSTOMER
GROUP BY shipping_type
HAVING shipping_type IN ('Standard','Express');

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,ROUND(AVG(`purchase_amount_(usd)`),2) AS Average_Spend,SUM(`purchase_amount_(usd)`) AS Total_Revenue
FROM CUSTOMER
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(
	SUM(
		CASE WHEN discount_applied="Yes" THEN 1 ELSE 0 END
        ) /COUNT(*)*100,2) 
	AS Discount_Percent
FROM CUSTOMER
GROUP BY item_purchased
ORDER BY Discount_Percent DESC 
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT CASE 
		WHEN previous_purchases IN (0,1) THEN "NEW"
		WHEN previous_purchases BETWEEN 2 AND 10 THEN "RETURNING"
		ELSE "LOYAL"
		END AS Customer_Segment ,
COUNT(*) AS Count_Segment 
FROM CUSTOMER
GROUP BY Customer_Segment 
ORDER BY Count_Segment  DESC ;

-- Q8. What are the top 3 most purchased products within each category? 
WITH TOP_RANK_TABLE AS (
SELECT category,item_purchased,COUNT(customer_id) AS Product_Count,
ROW_NUMBER() OVER (partition by category ORDER BY COUNT(customer_id) DESC) AS RANKING
FROM CUSTOMER
GROUP BY category,item_purchased)
SELECT * FROM TOP_RANK_TABLE WHERE RANKING<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS COUNT
FROM CUSTOMER
WHERE previous_purchases>5
GROUP BY subscription_status
ORDER BY COUNT DESC ;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group ,sum(`purchase_amount_(usd)`) AS Total_revenue
FROM CUSTOMER
GROUP BY age_group
ORDER BY Total_revenue DESC;
